### PR TITLE
Add Vietnamese translation 

### PR DESCRIPTION
**Pull request by Ele7o**
I use the english translation as a base

### CODE REVIEW

**Comment by KurtBestor** [comment]
Please change "vn" to "vi" (ISO 639-1 standard).

See: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by Ele7o** [comment]
Fixed

**Comment by KurtBestor** [comment]
As well as the filename: `tr_vn.hdl` -> `tr_vi.hdl`

**Comment by Ele7o** [comment]
Sorry, my bad

**Pull request merged**
